"""
Configuration - Configurações do sistema
"""

CAMERA_DEVICE_ID = 0
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30

HAND_DETECTION_CONFIDENCE = 0.7
HAND_TRACKING_CONFIDENCE = 0.7
MAX_HANDS = 1

PINCH_THRESHOLD = 0.04
SWIPE_THRESHOLD = 0.15
SWIPE_VELOCITY_THRESHOLD = 0.3
CLICK_COOLDOWN = 0.8
SCROLL_GESTURE_THRESHOLD = 0.08

EMA_ALPHA = 0.3
DEAD_ZONE = 0.02

SCROLL_AMOUNT = 3
SCROLL_MAX_AMOUNT = 15
SCROLL_INTERVAL = 0.05
SCROLL_MIN_INTERVAL = 0.01
SCROLL_DIRECTION_THRESHOLD = 0.02
SCROLL_MIN_VELOCITY = 0.2
SCROLL_MAX_VELOCITY_THRESHOLD = 0.5

SCROLL_UP_ZONE = 0.55
SCROLL_UP_BASE_VELOCITY = 0.5
SCROLL_UP_VELOCITY_BOOST = 1.8
SCROLL_UP_THRESHOLD_MULTIPLIER = 0.6
SCROLL_UP_AMOUNT_BOOST = 1.5
SCROLL_UP_INTERVAL_MULTIPLIER = 0.7

NO_HAND_TIMEOUT = 2.0

DEBUG_MODE = False

